"use client";
import { useEffect,useState } from "react"; import { useParams,useRouter } from "next/navigation"; import { CalendarDays,Pause,Play,RefreshCw,Save,Trash2 } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout"; import { Badge,PageHeader,StatCard,Surface } from "@/components/design-system/ui"; import { api,Hunter,PriceHistory } from "@/lib/api";
export default function TripDetailsPage(){const {id}=useParams<{id:string}>();const router=useRouter();const [h,setH]=useState<Hunter|null>(null);const [history,setHistory]=useState<PriceHistory[]>([]);const [edit,setEdit]=useState(false);const [form,setForm]=useState({name:"",maxPrice:""});const [error,setError]=useState("");
 const load=async()=>{try{const [hunter,hist]=await Promise.all([api.hunter(id),api.history(id)]);setH(hunter);setHistory(hist);setForm({name:hunter.name,maxPrice:String(hunter.maxPrice)});setError("")}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar")}};useEffect(()=>{void load()},[id]);if(!h)return <AppLayout><div className="mx-auto max-w-[1500px]">{error||"Carregando Hunter..."}</div></AppLayout>;
 const saving=Math.max(0,(h.previousPrice??0)-(h.currentPrice??0));
 async function run(){await api.runHunter(id);await load()} async function toggle(){await api.setStatus(id,h!.status==="ACTIVE"?"PAUSED":"ACTIVE");await load()} async function save(){await api.updateHunter(id,{name:form.name,maxPrice:Number(form.maxPrice)});setEdit(false);await load()}
 return <AppLayout><div className="mx-auto max-w-[1500px]"><PageHeader eyebrow="Detalhes da viagem" title={h.name} description={`${h.origin} → ${h.destination} · monitoramento real`} action={<div className="flex gap-2"><Badge tone={h.status==="ACTIVE"?"success":"warning"}>{h.status}</Badge><button onClick={run} className="rounded-xl bg-[#eef3ff] p-3 text-[#1557ff]" title="Executar busca"><RefreshCw className="h-4 w-4"/></button><button onClick={toggle} className="rounded-xl bg-[#f5f2ff] p-3 text-[#7058e8]">{h.status==="ACTIVE"?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}</button><button onClick={()=>setEdit(!edit)} className="rounded-xl bg-white px-4 text-sm font-bold">Editar</button><button onClick={async()=>{if(confirm("Excluir este Hunter?")){await api.deleteHunter(id);router.push("/trips")}}} className="rounded-xl bg-red-50 p-3 text-red-500"><Trash2 className="h-4 w-4"/></button></div>}/>
 {edit&&<Surface className="mt-5 p-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label><label className="text-sm font-bold">Teto de preço<input type="number" value={form.maxPrice} onChange={e=>setForm({...form,maxPrice:e.target.value})} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label></div><button onClick={save} className="mt-4 flex items-center gap-2 rounded-xl bg-[#101a3a] px-4 py-3 text-sm font-bold text-white"><Save className="h-4 w-4"/>Salvar alterações</button></Surface>}
 <div className="stagger mt-7 grid gap-4 md:grid-cols-3"><StatCard label="Tarifa atual" value={h.currentPrice?`R$ ${h.currentPrice.toLocaleString("pt-BR")}`:"—"} helper={`Teto: R$ ${h.maxPrice.toLocaleString("pt-BR")}`} accent="purple"/><StatCard label="Score" value={String(h.score??"—")} helper={`Confiança ${h.confidence??"—"}%`} accent="green"/><StatCard label="Variação" value={`R$ ${saving.toLocaleString("pt-BR")}`} helper="Comparada à medição anterior" accent="blue"/></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_1fr]"><Surface className="p-6"><h2 className="text-lg font-bold">Histórico de preço</h2><p className="mt-1 text-xs text-[#8290aa]">{history.length} medições registradas</p><div className="mt-5 space-y-2">{history.length===0?<p className="text-sm text-[#71809d]">Execute uma busca para começar o histórico.</p>:history.slice().reverse().map((x,i)=><div key={x.id??i} className="flex justify-between rounded-2xl bg-[#f8f9fd] p-4"><span className="text-sm text-[#71809d]">{new Date(x.capturedAt??x.createdAt??Date.now()).toLocaleString("pt-BR")}</span><span className="font-bold">R$ {(x.price??x.currentPrice??0).toLocaleString("pt-BR")}</span><span className="text-sm font-bold text-[#6f58e8]">score {x.score??"—"}</span></div>)}</div></Surface><Surface className="p-6"><h2 className="text-lg font-bold">Configuração</h2><div className="mt-5 space-y-3 text-sm"><p><b>Origem:</b> {h.origin}</p><p><b>Destino:</b> {h.destination}</p><p><b>Ida:</b> {new Date(h.departureFrom).toLocaleDateString("pt-BR")}</p><p><b>Status:</b> {h.status}</p></div></Surface></div>
 <Surface className="mt-5 p-6"><div className="flex items-center gap-3"><CalendarDays className="h-5 w-5 text-[#6f58e8]"/><h2 className="text-lg font-bold">Linha do tempo real</h2></div><p className="mt-3 text-sm text-[#71809d]">As medições acima são carregadas de /api/hunters/{id}/history. Nenhum dado mock é utilizado nesta tela.</p></Surface></div></AppLayout>}
