"use client";
import Link from "next/link"; import { useEffect,useState } from "react"; import { Plus,Search,Pause,Play,Trash2,RefreshCw } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout"; import { Badge,PageHeader,PrimaryButton,Surface } from "@/components/design-system/ui"; import { api,Hunter } from "@/lib/api";
export default function TripsPage(){const [items,setItems]=useState<Hunter[]>([]);const [q,setQ]=useState("");const [busy,setBusy]=useState("");const [error,setError]=useState("");
 const load=async()=>{try{setItems(await api.hunters());setError("")}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar")}};useEffect(()=>{void load()},[]);
 async function action(id:string,fn:()=>Promise<unknown>){setBusy(id);try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:"Falha na ação")}finally{setBusy("")}}
 const list=items.filter(h=>`${h.name} ${h.origin} ${h.destination}`.toLowerCase().includes(q.toLowerCase()));
 return <AppLayout><div className="mx-auto max-w-[1500px]"><PageHeader eyebrow="Flight Hunter" title="Viagens monitoradas" description="Rotas e recomendações vindas diretamente do backend." action={<Link href="/new-hunter"><PrimaryButton><span className="flex items-center gap-2"><Plus className="h-4 w-4"/>Novo Hunter</span></PrimaryButton></Link>}/>
 <Surface className="mt-7 p-3" hover={false}><div className="flex items-center gap-3 rounded-2xl bg-[#f8f9fd] px-4"><Search className="h-4 w-4 text-[#94a0b5]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome, origem ou destino..." className="h-12 w-full bg-transparent text-sm outline-none"/></div></Surface>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}
 <div className="stagger mt-5 grid gap-4">{list.map(h=><Surface key={h.id} className="grid gap-5 p-5 xl:grid-cols-[1.4fr_.8fr_.8fr_.8fr_230px] xl:items-center"><Link href={`/trips/${h.id}`}><p className="text-lg font-bold text-[#101a3a]">{h.name}</p><p className="mt-1 text-xs text-[#7b87a3]">{h.origin} → {h.destination}</p></Link><div><p className="text-[11px] text-[#7b87a3]">Tarifa atual</p><p className="mt-1 text-xl font-bold">{h.currentPrice?`R$ ${h.currentPrice.toLocaleString("pt-BR")}`:"—"}</p></div><div><p className="text-[11px] text-[#7b87a3]">Score</p><p className="mt-1 text-xl font-bold">{h.score??"—"}</p></div><div><p className="text-[11px] text-[#7b87a3]">Status</p><div className="mt-2"><Badge tone={h.status==="ACTIVE"?"success":"warning"}>{h.status==="ACTIVE"?"ATIVO":"PAUSADO"}</Badge></div></div><div className="flex justify-end gap-2"><button title="Executar busca" disabled={busy===h.id} onClick={()=>action(h.id,()=>api.runHunter(h.id))} className="rounded-xl bg-[#eef3ff] p-3 text-[#1557ff]"><RefreshCw className="h-4 w-4"/></button><button title={h.status==="ACTIVE"?"Pausar":"Ativar"} onClick={()=>action(h.id,()=>api.setStatus(h.id,h.status==="ACTIVE"?"PAUSED":"ACTIVE"))} className="rounded-xl bg-[#f5f2ff] p-3 text-[#7058e8]">{h.status==="ACTIVE"?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}</button><button title="Excluir" onClick={()=>{if(confirm("Excluir este Hunter?"))void action(h.id,()=>api.deleteHunter(h.id))}} className="rounded-xl bg-red-50 p-3 text-red-500"><Trash2 className="h-4 w-4"/></button><Link href={`/trips/${h.id}`} className="rounded-xl px-3 py-3 text-sm font-bold text-[#1557ff]">Detalhes →</Link></div></Surface>)}</div></div></AppLayout>}
